package entities;
// Generated 26/03/2018 00:49:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Turn generated by hbm2java
 */
public class Turn  implements java.io.Serializable {


     private Integer id;
     private Companyschedule companyschedule;
     private Guardschedule guardschedule;
     private Date turndate;

    public Turn() {
    }

    public Turn(Companyschedule companyschedule, Guardschedule guardschedule, Date turndate) {
       this.companyschedule = companyschedule;
       this.guardschedule = guardschedule;
       this.turndate = turndate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Companyschedule getCompanyschedule() {
        return this.companyschedule;
    }
    
    public void setCompanyschedule(Companyschedule companyschedule) {
        this.companyschedule = companyschedule;
    }
    public Guardschedule getGuardschedule() {
        return this.guardschedule;
    }
    
    public void setGuardschedule(Guardschedule guardschedule) {
        this.guardschedule = guardschedule;
    }
    public Date getTurndate() {
        return this.turndate;
    }
    
    public void setTurndate(Date turndate) {
        this.turndate = turndate;
    }




}


